In [1]:
from data_file.Airfoil_Self_Noise import Airfoil_Self_Noise as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Airfoil_Self_Noise"
task = "regression"

2025-08-04 15:45:56,248 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.015958  0.015572  0.014338  0.015289  0.000691
DFS           0.016311  0.015261  0.015065  0.015546  0.000547
AutoFeat      0.015958  0.015572  0.014338  0.015289  0.000691
OpenFE        0.014443  0.013900  0.013864  0.014069  0.000265
LLMFE         0.016559  0.013997  0.013430  0.014662  0.001361

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.015958  0.015572  0.014338  0.015289  0.000691
MALMAS(ours)  0.013573  0.013269  0.012492  0.013111  0.000455