In [1]:
from data_file.Bike import Bike as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Bike"
task = "regression"

2025-08-04 15:46:07,695 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.228925  0.229925  0.230067  0.229639  0.000508
DFS           0.227267  0.221622  0.227159  0.225349  0.002636
AutoFeat      0.228925  0.229925  0.230067  0.229639  0.000508
OpenFE        0.215837  0.210223  0.214289  0.213450  0.002367
LLMFE         0.222282  0.228447  0.224359  0.225029  0.002561

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.228925  0.229925  0.230067  0.229639  0.000508
MALMAS(ours)  0.215146  0.215560  0.213141  0.214616  0.001056