In [1]:
from data_file.Crab_Age_Prediction import Crab_Age_Prediction as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Crab_Age_Prediction"
task = "regression"

2025-08-04 15:46:12,721 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.217754  0.223916  0.217100  0.219590  0.003070
DFS           0.218963  0.219345  0.214168  0.217492  0.002355
AutoFeat      0.219569  0.223916  0.216640  0.220042  0.002989
OpenFE        0.216202  0.212858  0.211895  0.213652  0.001846
LLMFE         0.220897  0.218781  0.215715  0.218464  0.002127

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.217754  0.223916  0.217100  0.219590  0.003070
MALMAS(ours)  0.214651  0.213978  0.209811  0.212814  0.002141