In [1]:
from data_file.Energy_Efficiency_Y1 import Energy_Efficiency_Y1 as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Energy_Efficiency_Y1"
task = "regression"

2025-08-04 15:46:27,568 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.018236  0.018716  0.016797  0.017916  0.000816
DFS           0.017574  0.016416  0.015825  0.016605  0.000727
AutoFeat      0.018236  0.018716  0.016797  0.017916  0.000816
OpenFE        0.017900  0.018592  0.016178  0.017557  0.001015
LLMFE         0.018256  0.018835  0.017870  0.018320  0.000397

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    temp=1.2,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.018236  0.018716  0.016797  0.017916  0.000816
MALMAS(ours)  0.017019  0.017663  0.016163  0.016948  0.000614