In [1]:
from data_file.House_Price import House_Price as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "House_Price"
task = "regression"

2025-08-04 15:46:31,276 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.174747  0.177744  0.166579  0.173024  0.004718
DFS           0.205704  0.168026  0.164650  0.179460  0.018609
AutoFeat      0.174747  0.177744  0.166579  0.173024  0.004718
OpenFE        0.159736  0.160955  0.161646  0.160779  0.000790
LLMFE         0.170217  0.158202  0.165397  0.164605  0.004937

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

Has loaded local file:D:\code_management\idea\mypro\data_file\House_Price\enriched_description.json
[MALMAS] Loaded cached feature.
Has loaded local file:D:\code_management\idea\mypro\data_file\House_Price\enriched_description.json
[MALMAS] Loaded cached feature.
Has loaded local file:D:\code_management\idea\mypro\data_file\House_Price\enriched_description.json
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.174747  0.177744  0.166579  0.173024  0.004718
MALMAS(ours)  0.157638  0.159387  0.149219  0.155415  0.004439