In [1]:
from data_file.Insurance import Insurance as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Insurance"
task = "regression"

2025-08-04 15:46:39,866 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_nrmse = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    verbose=False
)
baseline_summary_nrmse

                     0         1         2      mean       std
xgboost_base  0.364475  0.360593  0.375850  0.366973  0.006474
DFS           0.372392  0.351403  0.372004  0.365267  0.009804
AutoFeat      0.364475  0.360593  0.375850  0.366973  0.006474
OpenFE        0.378166  0.389958  0.375846  0.381323  0.006179
LLMFE         0.364475  0.348550  0.361684  0.358236  0.006944

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=3,
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.364475  0.360593  0.375850  0.366973  0.006474
MALMAS(ours)  0.357230  0.351776  0.355761  0.354922  0.002304