In [1]:
from data_file.Medical_Cost_Personal import Medical_Cost_Personal as read_data
from baselines.baseline_func import run_baseline_experiments_for_Regressor
import global_config
from main_demo.main_func import *
from main_demo.pipeline import *
from main_demo.model_factory import *

prompt_path_list = global_config.prompt_path_list
task_name = "Medical_Cost_Personal"
task = "regression"

2025-08-04 15:46:45,156 INFO: No config file found at C:\Users\lenovo\.openml\config, using default configuration.

In [2]:
baseline_summary_auc = run_baseline_experiments_for_Regressor(
    task=task,
    model_name="xgboost",
    task_name=task_name,
    read_data_class=read_data,
    metric="auc",
    verbose=False
)
baseline_summary_auc

                     0         1         2      mean       std
xgboost_base  0.364475  0.371017  0.369740  0.368411  0.002831
DFS           0.372392  0.375118  0.370705  0.372739  0.001818
AutoFeat      0.364475  0.371017  0.369740  0.368411  0.002831
OpenFE        0.378166  0.375396  0.376464  0.376675  0.001141
LLMFE         0.361952  0.373901  0.373341  0.369731  0.005505

In [3]:
MALMAS_summary_nrmse = await MALMAS_random_experiments_async(
    task_name=task_name,
    task=task,
    read_data_class=read_data,
    model_name="xgboost",
    metric="nrmse",
    prompt_path_list=prompt_path_list,
    Nround=4,
    min_effective=2,
    long_memory_feature_num=4,
    temp=1.0,
    verbose=False
)
MALMAS_summary_nrmse

[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.
[MALMAS] Loaded cached feature.

                     0         1         2      mean       std
xgboost_base  0.364475  0.371017  0.369740  0.368411  0.002831
MALMAS(ours)  0.352975  0.353389  0.359439  0.355268  0.002954